# actionlint configuration
# https://github.com/rhysd/actionlint/blob/main/docs/config.md

self-hosted-runner:
  labels:
    # Using GitHub-hosted runners (ubuntu-latest, windows-latest)
    - ubuntu-latest
    - windows-latest

# Ignore patterns for known issues
paths:
  .github/workflows/**/*.yml:
    ignore:
      # Ignore shellcheck warnings (we run shellcheck separately)
      - "shellcheck reported issue.+"
      # Ignore intentional if: false for disabled jobs
      - 'constant expression "false" in condition'
