#!/bin/bash
# ================================================================
# Phase 5B Efficient Mode - Iteration Loop Controller
# ================================================================
# This script controls the iteration loop for Phase 5B API testing
# Uses Claude CLI with Claude In Chrome MCP for browser automation
# ================================================================

# Note: set -e removed intentionally — Claude CLI may return non-zero exit codes
# that should not terminate the iteration loop

# Fix encoding: ensure UTF-8 on Japanese Windows (Git Bash inherits CP932)
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export PYTHONIOENCODING=utf-8

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILL_REF_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
CONFIG_FILE="$SKILL_REF_DIR/config/phase5-loop-control.json"
PROMPT_FILE="$SKILL_REF_DIR/prompts/phase5b-api-tests-efficient.md"
# PROJECT_ROOT is the user's workspace (argument or pwd)
PROJECT_ROOT="${WORKSPACE_DIR:-$(pwd)}"
LOG_DIR="$PROJECT_ROOT/test-logs"

# Create log directory
mkdir -p "$LOG_DIR"

# Real-time log helper: outputs to both console and realtime log file
log_msg() {
    echo "$1"
    [ -n "$REALTIME_LOG" ] && echo "[$(date +%H:%M:%S)] $1" >> "$REALTIME_LOG"
}

# ================================================================
# Check Claude In Chrome MCP Connectivity
# ================================================================
check_chrome_mcp() {
    log_msg "[CHECK] Verifying Claude In Chrome MCP..."

    # Check 1: .mcp.json exists in workspace (generated by run-all.ps1)
    if [ ! -f "$PROJECT_ROOT/.mcp.json" ]; then
        log_msg "[WARN] .mcp.json not found in $PROJECT_ROOT — Chrome MCP may not be available"
    else
        log_msg "[OK] .mcp.json found in workspace"
    fi

    # Check 2: Chrome DevTools Protocol HTTP check (fast, no claude CLI needed)
    local cdp_port
    for port in 9222 9223 9224 9225 9226 9227 9228 9229; do
        if curl -s --max-time 3 "http://127.0.0.1:$port/json/version" >/dev/null 2>&1; then
            cdp_port=$port
            break
        fi
    done

    if [ -n "$cdp_port" ]; then
        local browser_info
        browser_info=$(curl -s --max-time 3 "http://127.0.0.1:$cdp_port/json/version" 2>/dev/null | grep -o '"Browser":"[^"]*"' | head -1)
        log_msg "[OK] Chrome DevTools Protocol available on port $cdp_port ($browser_info)"
        return 0
    fi

    log_msg "[ERROR] Claude In Chrome MCP NOT available!"
    log_msg "[ERROR] Please: 1) Open Chrome with --remote-debugging-port=9222  2) Verify port is accessible"
    return 1
}

# ================================================================
# Load Configuration
# ================================================================
load_config() {
    # Default values
    MAX_ITERATIONS=15
    TARGET_PASS_RATE=95
    EARLY_EXIT_THRESHOLD=3
    ITERATION_TIMEOUT=3600

    # Load from config file if exists
    # NOTE: pyenv-win .cmd shims break multiline python3 -c strings,
    # so we write Python code to a temp file and execute it.
    if [ -f "$CONFIG_FILE" ]; then
        local tmp_py
        tmp_py=$(mktemp /tmp/cfg_XXXXXX.py)
        cat > "$tmp_py" << 'PYEOF'
import json, sys
try:
    with open(sys.argv[1], encoding='utf-8') as f:
        cfg = json.load(f)
    print(cfg.get('phase5b_bugfix', {}).get('max_iterations', cfg.get('iteration_control', {}).get('max_iterations', 15)))
except:
    print(15)
PYEOF
        MAX_ITERATIONS=$(python3 "$tmp_py" "$CONFIG_FILE" 2>/dev/null || echo "15")

        cat > "$tmp_py" << 'PYEOF'
import json, sys
try:
    with open(sys.argv[1], encoding='utf-8') as f:
        cfg = json.load(f)
    print(cfg.get('global', {}).get('target_pass_rate_5b', cfg.get('global', {}).get('target_pass_rate', 95)))
except:
    print(95)
PYEOF
        TARGET_PASS_RATE=$(python3 "$tmp_py" "$CONFIG_FILE" 2>/dev/null || echo "95")
        rm -f "$tmp_py"
    fi

    # Environment variable overrides
    MAX_ITERATIONS="${BUGFIX_MAX_ITERATIONS:-$MAX_ITERATIONS}"
    TARGET_PASS_RATE="${BUGFIX_TARGET_PASS_RATE:-$TARGET_PASS_RATE}"
    EARLY_EXIT_THRESHOLD="${BUGFIX_EARLY_EXIT_THRESHOLD:-$EARLY_EXIT_THRESHOLD}"

    log_msg "============================================================"
    log_msg "Phase 5B Efficient Mode - Configuration"
    log_msg "============================================================"
    log_msg "Max Iterations: $MAX_ITERATIONS"
    log_msg "Target Pass Rate: $TARGET_PASS_RATE%"
    log_msg "Early Exit Threshold: $EARLY_EXIT_THRESHOLD"
    log_msg "Iteration Timeout: ${ITERATION_TIMEOUT}s"
    log_msg "============================================================"
}

# ================================================================
# Get Pass Rate from Results
# ================================================================
get_pass_rate() {
    RESULT_FILE="$LOG_DIR/phase5b_efficient_test_results.json"

    if [ -f "$RESULT_FILE" ]; then
        # NOTE: pyenv-win .cmd shims break multiline python3 -c strings,
        # so we write Python code to a temp file and execute it.
        local tmp_py
        tmp_py=$(mktemp /tmp/rate_XXXXXX.py)
        cat > "$tmp_py" << 'PYEOF'
import json, sys
def to_num(v):
    if v is None: return 0
    if isinstance(v, (int, float)): return float(v)
    if isinstance(v, str):
        v = v.strip().rstrip('%')
        try: return float(v)
        except: return 0
    return 0
try:
    with open(sys.argv[1], encoding='utf-8') as f:
        data = json.load(f)
    rate = 0
    # Try all known pass_rate key variants (Claude generates unpredictable names)
    for key in ['pass_rate', 'passRate', 'adjusted_pass_rate', 'adjustedPassRate', 'actual_pass_rate', 'actualPassRate']:
        if key in data and data[key]:
            rate = to_num(data[key]); break
    # Check summary sub-object
    if not rate and 'summary' in data:
        s = data['summary']
        for key in ['pass_rate', 'passRate', 'adjusted_pass_rate', 'adjustedPassRate', 'actual_pass_rate', 'actualPassRate']:
            if key in s and s[key]:
                rate = to_num(s[key]); break
    # Fallback: calculate from passed/total (various key names)
    if not rate:
        total = 0
        for key in ['totalTests', 'total_tests', 'total', 'total_pages_tested', 'totalPagesTested', 'total_endpoints', 'totalEndpoints']:
            if key in data and data[key]:
                total = int(data[key]); break
        passed = 0
        for key in ['passed', 'tests_passed', 'total_pages_passed', 'totalPagesPassed', 'pages_passed', 'endpoints_passed']:
            if key in data and data[key]:
                passed = int(data[key]); break
        if total > 0:
            rate = round(passed / total * 100, 1)
    print(rate)
except:
    print(0)
PYEOF
        local result
        result=$(python3 "$tmp_py" "$RESULT_FILE" 2>/dev/null || echo "0")
        rm -f "$tmp_py"
        echo "$result"
    else
        echo "0"
    fi
}

# ================================================================
# Run Single Iteration
# ================================================================
run_iteration() {
    local iteration=$1
    log_msg ""
    log_msg "============================================================"
    log_msg "ITERATION $iteration/$MAX_ITERATIONS"
    log_msg "============================================================"
    
    # Build prompt with iteration context
    local prompt_file_abs="$PROMPT_FILE"
    local backend_url="${AIDEV_BACKEND_URL:-http://localhost:8000/docs}"

    # Load Phase 5A test data directly into the prompt (so Claude doesn't need to Read it)
    local test_data_context=""
    local seed_file="$LOG_DIR/test_data_seed.json"
    local auth_file="$LOG_DIR/phase5b_test_user.json"
    if [ -f "$seed_file" ]; then
        test_data_context="
=== PHASE 5A TEST DATA (ALREADY CREATED - USE THESE IDs) ===
$(cat "$seed_file")
=== END TEST DATA ===
"
        if [ -f "$auth_file" ]; then
            test_data_context="${test_data_context}
=== AUTH CREDENTIALS ===
$(cat "$auth_file")
=== END AUTH ===
"
        fi
        # Inject admin auth if available (for authorization scenario testing)
        local admin_auth_file="$LOG_DIR/phase5a_admin_user.json"
        if [ -f "$admin_auth_file" ]; then
            test_data_context="${test_data_context}
=== ADMIN AUTH CREDENTIALS (use for authorization scenario tests) ===
$(cat "$admin_auth_file")
=== END ADMIN AUTH ===
"
            log_msg "[INFO] Injected admin auth credentials into prompt"
        fi
        log_msg "[INFO] Injected Phase 5A test data into prompt"
    else
        test_data_context="
WARNING: test-logs/test_data_seed.json NOT FOUND.
You MUST create test data yourself using javascript_tool:
1. Register user: POST /api/v1/auth/register {email, password, username}
2. Login: POST /api/v1/auth/login to get JWT token
3. Create entities needed for testing
4. Save all created IDs to test-logs/test_data_seed.json
"
        log_msg "[WARN] Phase 5A test data not found - Claude will create data"
    fi

    # Build previous results context for iterations 2+
    local prev_context=""
    local prev_result_file="$LOG_DIR/phase5b_efficient_test_results.json"
    if [ "$iteration" -gt 1 ] && [ -f "$prev_result_file" ]; then
        prev_context="
PREVIOUS ITERATION RESULTS: ${prev_result_file}
Read this file and prioritize fixing/re-testing FAILED tests.
Tests that already PASSED do not need re-running unless test data was lost."
    fi

    ITERATION_PROMPT="You are executing Phase 5B API Testing, iteration ${iteration}.

IMPORTANT: The backend is already running. Do NOT attempt to start it.
Swagger UI URL: ${backend_url}
Navigate to this URL in the browser to perform API tests.
${prev_context}

Read and execute ALL steps from the test specification file:
${prompt_file_abs}

${test_data_context}

MANDATORY EXECUTION METHOD:
All API tests MUST be performed via Claude In Chrome MCP browser automation ONLY.
PROHIBITED methods (do NOT use):
- curl / wget / httpie
- python requests / httpx / aiohttp
- Playwright / Puppeteer / Selenium
- Node.js fetch / axios
- Any non-MCP HTTP client

Required MCP tools:
- mcp__Claude_in_Chrome__tabs_context_mcp
- mcp__Claude_in_Chrome__navigate
- mcp__Claude_in_Chrome__read_page / find
- mcp__Claude_in_Chrome__computer (click/screenshot)
- mcp__Claude_in_Chrome__form_input
- mcp__Claude_in_Chrome__javascript_tool
- mcp__Claude_in_Chrome__read_network_requests

STEPS (execute in order):

Step 0: Call mcp__Claude_in_Chrome__tabs_context_mcp to verify MCP connection.
  If unavailable -> stop immediately and report error. Do NOT use alternatives.

Step 1: Load test data from Phase 5A (provided above in the prompt).
  - Parse the TEST DATA section above to extract entity IDs and auth token.
  - Use auth.token for Swagger UI Authorization (Bearer token).
  - NEVER hardcode id=1 or id=999. Use ONLY real IDs from test data.
  - If a specific entity is missing for a test, create it using javascript_tool
    and record the new ID.

Step 2: Set Authorization in Swagger UI (Bearer token from test data).

Step 3: Test ALL API endpoints — TWO-LAYER TESTING PROTOCOL

=== LAYER 1: CRUD Testing (Standard) ===
Test ALL API endpoints by category using real entity IDs from test data.
  - Use real entity IDs from the test data above.
  - 404 response = missing test data -> create the missing entity with
    javascript_tool, then retry the test. This is NOT an acceptable failure.
  - Bug found -> fix the code -> restart backend -> re-test.

=== LAYER 2: SCENARIO-BASED TESTING (MANDATORY if scenarios exist) ===
If the test data JSON contains a \"scenarios\" key, you MUST execute EVERY scenario.
This is NOT optional. Each scenario is a REQUIRED test case.

SCENARIO EXECUTION RULES:
1. Parse the \"scenarios\" object from the injected test data above.
2. Execute ALL entries in EACH category in order:

   [validation] For each entry:
     - Send the specified invalid payload to the target endpoint
     - Verify response status matches expected_status (e.g., 422)
     - Record PASS/FAIL with actual vs expected status

   [state_transitions] For each entry:
     - Use the specified record_id and attempt the state change
     - For VALID transitions: verify expected_status 200 and new state
     - For INVALID transitions: verify expected_status 400 and state unchanged

   [authorization] For each entry:
     - If auth_as=\"admin\", use ADMIN AUTH token from above
     - If auth_as=\"user\", use regular AUTH token from above
     - Send request to the specified endpoint
     - Verify response matches expected_status (200 vs 403)

   [business_constraints] For each entry:
     - Set up the constraint condition if needed (e.g., stock=0 product)
     - Send the request that should violate the constraint
     - Verify the expected error status (e.g., 400)

3. Include ALL scenario results in the results JSON under \"scenario_results\"

Step 4: Generate results file: test-logs/phase5b_efficient_test_results.json
  The results file MUST include:
  - total_tests: CRUD count + scenario count
  - passed: CRUD passed + scenario passed
  - pass_rate: calculated from total_tests and passed
  - crud_results: { total, passed, endpoints: [...] }
  - scenario_results (if scenarios were executed): {
      total, passed,
      validation: { total, passed, details: [...] },
      state_transitions: { total, passed, details: [...] },
      authorization: { total, passed, details: [...] },
      business_constraints: { total, passed, details: [...] }
    }
  IMPORTANT: pass_rate MUST include scenario test counts. Scenarios are NOT separate.

KEY REQUIREMENTS:
1. Use Claude In Chrome MCP for browser automation (the ONLY allowed method)
2. Use entity IDs from Phase 5A test data (injected above). Never guess IDs.
3. Test ALL API endpoints (LAYER 1). Use real created IDs. Never use id=999.
4. Execute ALL scenarios (LAYER 2) if \"scenarios\" key exists in test data.
5. If test data is insufficient, create more via javascript_tool.
6. Fix bugs immediately when found.
7. Generate results file: test-logs/phase5b_efficient_test_results.json
8. Target pass rate: ${TARGET_PASS_RATE}% (includes both CRUD and scenario tests)

Report test results when done."

    # Run Claude CLI via stdin pipe (NOT -p flag, which disables tools/MCP)
    # On timeout, use taskkill /T to kill entire process tree (Git Bash lacks GNU timeout/pkill)
    # NOTE: We run pipeline directly (no subshell) to avoid MSYS2 zombie subshell issue
    # where kill -0 $bg_pid keeps succeeding after all pipeline components have exited.
    # Instead, we detect completion by checking if the result JSON file was updated.
    cd "$PROJECT_ROOT"

    local RESULT_FILE="$LOG_DIR/phase5b_efficient_test_results.json"
    local iteration_start_epoch
    iteration_start_epoch=$(date +%s)

    # Remove stale result file so we can detect when a new one is written
    if [ -f "$RESULT_FILE" ]; then
        local result_mtime
        result_mtime=$(stat -c %Y "$RESULT_FILE" 2>/dev/null || echo 0)
    fi

    # Write output directly to file (avoids tee buffering issue on MSYS2
    # where tee uses full buffering in pipes and loses data on taskkill)
    local ITER_LOG="$LOG_DIR/phase5b_iteration_${iteration}.log"
    : > "$ITER_LOG"

    echo "$ITERATION_PROMPT" | claude --dangerously-skip-permissions --verbose > "$ITER_LOG" 2>&1 &
    local bg_pid=$!

    # Manual timeout monitoring with result-file-based completion detection
    # Also periodically streams new log lines to console and realtime log
    local elapsed=0
    local last_line_count=0
    while kill -0 $bg_pid 2>/dev/null; do
        sleep 10
        elapsed=$((elapsed + 10))

        # Stream new lines from iteration log to console and realtime log
        if [ -f "$ITER_LOG" ]; then
            local current_line_count
            current_line_count=$(wc -l < "$ITER_LOG" 2>/dev/null || echo 0)
            if [ "$current_line_count" -gt "$last_line_count" ]; then
                local skip=$((last_line_count + 1))
                tail -n +"$skip" "$ITER_LOG" 2>/dev/null | while IFS= read -r line; do
                    echo "$line"
                    [ -n "$REALTIME_LOG" ] && echo "[$(date +%H:%M:%S)] $line" >> "$REALTIME_LOG"
                done
                last_line_count=$current_line_count
            fi
        fi

        # MSYS2 workaround: check if result file was updated after iteration started
        # This catches the case where the subshell is zombie but work is already done
        if [ -f "$RESULT_FILE" ]; then
            local current_mtime
            current_mtime=$(stat -c %Y "$RESULT_FILE" 2>/dev/null || echo 0)
            if [ "$current_mtime" -gt "$iteration_start_epoch" ]; then
                log_msg "[INFO] Result file updated — iteration complete (pipeline cleanup)"
                sleep 5  # Allow final log flush
                taskkill.exe /T /F /PID $bg_pid >/dev/null 2>&1
                kill $bg_pid 2>/dev/null
                wait $bg_pid 2>/dev/null
                return 0
            fi
        fi

        if [ $elapsed -ge $ITERATION_TIMEOUT ]; then
            log_msg "[WARN] Iteration $iteration timed out after ${ITERATION_TIMEOUT}s — killing process tree"
            # Dump remaining log lines before killing
            if [ -f "$ITER_LOG" ]; then
                local final_count
                final_count=$(wc -l < "$ITER_LOG" 2>/dev/null || echo 0)
                if [ "$final_count" -gt "$last_line_count" ]; then
                    local skip=$((last_line_count + 1))
                    tail -n +"$skip" "$ITER_LOG" 2>/dev/null | while IFS= read -r line; do
                        echo "$line"
                        [ -n "$REALTIME_LOG" ] && echo "[$(date +%H:%M:%S)] $line" >> "$REALTIME_LOG"
                    done
                fi
            fi
            # Use Windows taskkill /T to kill subshell + all child processes (claude, tee, etc.)
            taskkill.exe /T /F /PID $bg_pid >/dev/null 2>&1
            # Fallback: also try kill in case taskkill missed anything
            kill $bg_pid 2>/dev/null
            wait $bg_pid 2>/dev/null
            return 124
        fi
    done

    wait $bg_pid 2>/dev/null
    local exit_code=$?
    return $exit_code
}

# ================================================================
# Main Loop
# ================================================================
main() {
    log_msg "+============================================================+"
    log_msg "|  Phase 5B Efficient Mode - Iteration Loop Controller       |"
    log_msg "+============================================================+"

    load_config

    # Pre-check: Claude In Chrome MCP must be available
    if ! check_chrome_mcp; then
        log_msg "[FATAL] Cannot proceed without Claude In Chrome MCP."
        exit 1
    fi

    iteration=1
    no_improvement_count=0
    previous_pass_rate=0

    while [ $iteration -le $MAX_ITERATIONS ]; do
        # Run iteration
        run_iteration $iteration || true

        # Get pass rate from results
        current_pass_rate=$(get_pass_rate)
        log_msg ""
        log_msg "[RESULT] Pass Rate: $current_pass_rate%"

        # Check if target achieved
        if [ $(python3 -c "print(1 if $current_pass_rate >= $TARGET_PASS_RATE else 0)" 2>/dev/null || echo "0") -eq 1 ]; then
            log_msg ""
            log_msg "+============================================================+"
            log_msg "|  [OK] SUCCESS: Target pass rate achieved!                   |"
            log_msg "|  Final Pass Rate: $current_pass_rate%                              |"
            log_msg "|  Iterations Used: $iteration                                        |"
            log_msg "+============================================================+"
            exit 0
        fi

        # Check early exit (strict less-than: plateau is NOT treated as no-improvement)
        if [ $(python3 -c "print(1 if $current_pass_rate < $previous_pass_rate else 0)" 2>/dev/null || echo "0") -eq 1 ]; then
            no_improvement_count=$((no_improvement_count + 1))
            log_msg "[WARN] No improvement ($no_improvement_count/$EARLY_EXIT_THRESHOLD)"

            if [ $no_improvement_count -ge $EARLY_EXIT_THRESHOLD ]; then
                log_msg ""
                log_msg "+============================================================+"
                log_msg "|  [WARN] EARLY EXIT: No improvement for $EARLY_EXIT_THRESHOLD iterations    |"
                log_msg "|  Final Pass Rate: $current_pass_rate%                              |"
                log_msg "|  Iterations Used: $iteration                                        |"
                log_msg "+============================================================+"
                exit 1
            fi
        else
            log_msg "[OK] Improvement: $previous_pass_rate% → $current_pass_rate%"
            no_improvement_count=0
        fi

        previous_pass_rate=$current_pass_rate
        iteration=$((iteration + 1))
    done

    # Max iterations reached
    log_msg ""
    log_msg "+============================================================+"
    log_msg "|  [FAIL] MAX_ITERATIONS_REACHED: $MAX_ITERATIONS iterations completed    |"
    log_msg "|  Final Pass Rate: $current_pass_rate%                              |"
    log_msg "+============================================================+"
    exit 1
}

main "$@"
