#!/bin/bash
# ================================================================
# Phase 5B Efficient Mode - Iteration Loop Controller
# ================================================================
# This script controls the iteration loop for Phase 5B API testing
# Uses Claude CLI with Claude In Chrome MCP for browser automation
# ================================================================

# Note: set -e removed intentionally — Claude CLI may return non-zero exit codes
# that should not terminate the iteration loop

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILL_REF_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
CONFIG_FILE="$SKILL_REF_DIR/config/phase5-loop-control.json"
PROMPT_FILE="$SKILL_REF_DIR/prompts/phase5b-api-tests-efficient.md"
# PROJECT_ROOT is the user's workspace (argument or pwd)
PROJECT_ROOT="${WORKSPACE_DIR:-$(pwd)}"
LOG_DIR="$PROJECT_ROOT/test-logs"

# Create log directory
mkdir -p "$LOG_DIR"

# Real-time log helper: outputs to both console and realtime log file
log_msg() {
    echo "$1"
    [ -n "$REALTIME_LOG" ] && echo "[$(date +%H:%M:%S)] $1" >> "$REALTIME_LOG"
}

# ================================================================
# Check Claude In Chrome MCP Connectivity
# ================================================================
check_chrome_mcp() {
    log_msg "[CHECK] Verifying Claude In Chrome MCP..."

    # Check 1: .mcp.json exists in workspace (generated by run-all.ps1)
    if [ ! -f "$PROJECT_ROOT/.mcp.json" ]; then
        log_msg "[WARN] .mcp.json not found in $PROJECT_ROOT — Chrome MCP may not be available"
    else
        log_msg "[OK] .mcp.json found in workspace"
    fi

    # Check 2: Chrome DevTools Protocol HTTP check (fast, no claude CLI needed)
    local cdp_port
    for port in 9222 9223 9224 9225 9226 9227 9228 9229; do
        if curl -s --max-time 3 "http://127.0.0.1:$port/json/version" >/dev/null 2>&1; then
            cdp_port=$port
            break
        fi
    done

    if [ -n "$cdp_port" ]; then
        local browser_info
        browser_info=$(curl -s --max-time 3 "http://127.0.0.1:$cdp_port/json/version" 2>/dev/null | grep -o '"Browser":"[^"]*"' | head -1)
        log_msg "[OK] Chrome DevTools Protocol available on port $cdp_port ($browser_info)"
        return 0
    fi

    log_msg "[ERROR] Claude In Chrome MCP NOT available!"
    log_msg "[ERROR] Please: 1) Open Chrome with --remote-debugging-port=9222  2) Verify port is accessible"
    return 1
}

# ================================================================
# Load Configuration
# ================================================================
load_config() {
    # Default values
    MAX_ITERATIONS=15
    TARGET_PASS_RATE=95
    EARLY_EXIT_THRESHOLD=3
    ITERATION_TIMEOUT=1800

    # Load from config file if exists
    # NOTE: pyenv-win .cmd shims break multiline python3 -c strings,
    # so we write Python code to a temp file and execute it.
    if [ -f "$CONFIG_FILE" ]; then
        local tmp_py
        tmp_py=$(mktemp /tmp/cfg_XXXXXX.py)
        cat > "$tmp_py" << 'PYEOF'
import json, sys
try:
    with open(sys.argv[1], encoding='utf-8') as f:
        cfg = json.load(f)
    print(cfg.get('phase5b_bugfix', {}).get('max_iterations', cfg.get('iteration_control', {}).get('max_iterations', 15)))
except:
    print(15)
PYEOF
        MAX_ITERATIONS=$(python3 "$tmp_py" "$CONFIG_FILE" 2>/dev/null || echo "15")

        cat > "$tmp_py" << 'PYEOF'
import json, sys
try:
    with open(sys.argv[1], encoding='utf-8') as f:
        cfg = json.load(f)
    print(cfg.get('global', {}).get('target_pass_rate_5b', cfg.get('global', {}).get('target_pass_rate', 95)))
except:
    print(95)
PYEOF
        TARGET_PASS_RATE=$(python3 "$tmp_py" "$CONFIG_FILE" 2>/dev/null || echo "95")
        rm -f "$tmp_py"
    fi

    # Environment variable overrides
    MAX_ITERATIONS="${BUGFIX_MAX_ITERATIONS:-$MAX_ITERATIONS}"
    TARGET_PASS_RATE="${BUGFIX_TARGET_PASS_RATE:-$TARGET_PASS_RATE}"
    EARLY_EXIT_THRESHOLD="${BUGFIX_EARLY_EXIT_THRESHOLD:-$EARLY_EXIT_THRESHOLD}"

    log_msg "════════════════════════════════════════════════════════════"
    log_msg "Phase 5B Efficient Mode - Configuration"
    log_msg "════════════════════════════════════════════════════════════"
    log_msg "Max Iterations: $MAX_ITERATIONS"
    log_msg "Target Pass Rate: $TARGET_PASS_RATE%"
    log_msg "Early Exit Threshold: $EARLY_EXIT_THRESHOLD"
    log_msg "Iteration Timeout: ${ITERATION_TIMEOUT}s"
    log_msg "════════════════════════════════════════════════════════════"
}

# ================================================================
# Get Pass Rate from Results
# ================================================================
get_pass_rate() {
    RESULT_FILE="$LOG_DIR/phase5b_efficient_test_results.json"

    if [ -f "$RESULT_FILE" ]; then
        # NOTE: pyenv-win .cmd shims break multiline python3 -c strings,
        # so we write Python code to a temp file and execute it.
        local tmp_py
        tmp_py=$(mktemp /tmp/rate_XXXXXX.py)
        cat > "$tmp_py" << 'PYEOF'
import json, sys
try:
    with open(sys.argv[1], encoding='utf-8') as f:
        data = json.load(f)
    rate = 0
    rate = data.get('adjusted_pass_rate') or data.get('pass_rate') or 0
    if not rate:
        rate_str = data.get('passRate', data.get('adjustedPassRate', ''))
        if isinstance(rate_str, str):
            rate = float(rate_str.replace('%', '')) if rate_str else 0
        else:
            rate = float(rate_str) if rate_str else 0
    if not rate and 'summary' in data:
        s = data['summary']
        rate_str = s.get('passRate', s.get('pass_rate', s.get('adjusted_pass_rate', '')))
        if isinstance(rate_str, str):
            rate = float(rate_str.replace('%', '')) if rate_str else 0
        else:
            rate = float(rate_str) if rate_str else 0
    if not rate:
        total = data.get('totalTests', data.get('total_tests', data.get('total', 0)))
        passed = data.get('passed', data.get('tests_passed', 0))
        if total > 0:
            rate = round(passed / total * 100, 1)
    print(rate)
except:
    print(0)
PYEOF
        local result
        result=$(python3 "$tmp_py" "$RESULT_FILE" 2>/dev/null || echo "0")
        rm -f "$tmp_py"
        echo "$result"
    else
        echo "0"
    fi
}

# ================================================================
# Run Single Iteration
# ================================================================
run_iteration() {
    local iteration=$1
    log_msg ""
    log_msg "════════════════════════════════════════════════════════════"
    log_msg "ITERATION $iteration/$MAX_ITERATIONS"
    log_msg "════════════════════════════════════════════════════════════"
    
    # Build prompt with iteration context
    local prompt_file_abs="$PROMPT_FILE"
    local backend_url="${AIDEV_BACKEND_URL:-http://localhost:8000/docs}"
    ITERATION_PROMPT="你正在执行 Phase 5B API 测试的第 ${iteration} 次迭代。

⚠️ 重要: バックエンドは既に起動済みです。起動を試みないでください。
Swagger UI URL: ${backend_url}
このURLにブラウザでアクセスしてAPIテストを実施してください。

请阅读并执行以下测试提示词文件中的所有步骤：
${prompt_file_abs}

⛔ 必须遵守的执行方法 ⛔:
所有 API 测试必须且只能通过 Claude In Chrome MCP 工具进行浏览器自动化。
严格禁止以下替代方法：
- curl / wget / httpie 直接调用 API
- python requests / httpx / aiohttp
- Playwright / Puppeteer / Selenium
- Node.js fetch / axios
- 任何非 MCP 的 HTTP 客户端

必须使用的 MCP 工具：
- mcp__Claude_in_Chrome__tabs_context_mcp
- mcp__Claude_in_Chrome__navigate
- mcp__Claude_in_Chrome__read_page / find
- mcp__Claude_in_Chrome__computer (点击/截图)
- mcp__Claude_in_Chrome__form_input
- mcp__Claude_in_Chrome__javascript_tool
- mcp__Claude_in_Chrome__read_network_requests

第一步：调用 mcp__Claude_in_Chrome__tabs_context_mcp 验证 MCP 连接。
如果不可用 → 立即停止并报告错误，不要使用替代方案。

关键要求：
1. 使用 Claude In Chrome MCP 进行浏览器自动化（唯一允许的方法）
2. 测试所有 API 端点
3. 发现 bug 后立即修复
4. 生成结果文件: test-logs/phase5b_efficient_test_results.json
5. 目标通过率: ${TARGET_PASS_RATE}%

完成后请报告测试结果。"

    # Run Claude CLI via stdin pipe (NOT -p flag, which disables tools/MCP)
    # On timeout, use taskkill /T to kill entire process tree (Git Bash lacks GNU timeout/pkill)
    # NOTE: We run pipeline directly (no subshell) to avoid MSYS2 zombie subshell issue
    # where kill -0 $bg_pid keeps succeeding after all pipeline components have exited.
    # Instead, we detect completion by checking if the result JSON file was updated.
    cd "$PROJECT_ROOT"

    local RESULT_FILE="$LOG_DIR/phase5b_efficient_test_results.json"
    local iteration_start_epoch
    iteration_start_epoch=$(date +%s)

    # Remove stale result file so we can detect when a new one is written
    if [ -f "$RESULT_FILE" ]; then
        local result_mtime
        result_mtime=$(stat -c %Y "$RESULT_FILE" 2>/dev/null || echo 0)
    fi

    if [ -n "$REALTIME_LOG" ]; then
        echo "$ITERATION_PROMPT" | claude --dangerously-skip-permissions --verbose 2>&1 | tee "$LOG_DIR/phase5b_iteration_${iteration}.log" | tee -a "$REALTIME_LOG" &
    else
        echo "$ITERATION_PROMPT" | claude --dangerously-skip-permissions --verbose 2>&1 | tee "$LOG_DIR/phase5b_iteration_${iteration}.log" &
    fi
    local bg_pid=$!

    # Manual timeout monitoring with result-file-based completion detection
    local elapsed=0
    while kill -0 $bg_pid 2>/dev/null; do
        sleep 10
        elapsed=$((elapsed + 10))

        # MSYS2 workaround: check if result file was updated after iteration started
        # This catches the case where the subshell is zombie but work is already done
        if [ -f "$RESULT_FILE" ]; then
            local current_mtime
            current_mtime=$(stat -c %Y "$RESULT_FILE" 2>/dev/null || echo 0)
            if [ "$current_mtime" -gt "$iteration_start_epoch" ]; then
                log_msg "[INFO] Result file updated — iteration complete (pipeline cleanup)"
                sleep 5  # Allow final log flush
                taskkill.exe /T /F /PID $bg_pid >/dev/null 2>&1
                kill $bg_pid 2>/dev/null
                wait $bg_pid 2>/dev/null
                return 0
            fi
        fi

        if [ $elapsed -ge $ITERATION_TIMEOUT ]; then
            log_msg "[WARN] Iteration $iteration timed out after ${ITERATION_TIMEOUT}s — killing process tree"
            # Use Windows taskkill /T to kill subshell + all child processes (claude, tee, etc.)
            taskkill.exe /T /F /PID $bg_pid >/dev/null 2>&1
            # Fallback: also try kill in case taskkill missed anything
            kill $bg_pid 2>/dev/null
            wait $bg_pid 2>/dev/null
            return 124
        fi
    done

    wait $bg_pid 2>/dev/null
    local exit_code=$?
    return $exit_code
}

# ================================================================
# Main Loop
# ================================================================
main() {
    log_msg "╔════════════════════════════════════════════════════════════╗"
    log_msg "║  Phase 5B Efficient Mode - Iteration Loop Controller       ║"
    log_msg "╚════════════════════════════════════════════════════════════╝"

    load_config

    # Pre-check: Claude In Chrome MCP must be available
    if ! check_chrome_mcp; then
        log_msg "[FATAL] Cannot proceed without Claude In Chrome MCP."
        exit 1
    fi

    iteration=1
    no_improvement_count=0
    previous_pass_rate=0

    while [ $iteration -le $MAX_ITERATIONS ]; do
        # Run iteration
        run_iteration $iteration || true

        # Get pass rate from results
        current_pass_rate=$(get_pass_rate)
        log_msg ""
        log_msg "[RESULT] Pass Rate: $current_pass_rate%"

        # Check if target achieved
        if [ $(python3 -c "print(1 if $current_pass_rate >= $TARGET_PASS_RATE else 0)" 2>/dev/null || echo "0") -eq 1 ]; then
            log_msg ""
            log_msg "╔════════════════════════════════════════════════════════════╗"
            log_msg "║  ✅ SUCCESS: Target pass rate achieved!                     ║"
            log_msg "║  Final Pass Rate: $current_pass_rate%                              ║"
            log_msg "║  Iterations Used: $iteration                                        ║"
            log_msg "╚════════════════════════════════════════════════════════════╝"
            exit 0
        fi

        # Check early exit (strict less-than: plateau is NOT treated as no-improvement)
        if [ $(python3 -c "print(1 if $current_pass_rate < $previous_pass_rate else 0)" 2>/dev/null || echo "0") -eq 1 ]; then
            no_improvement_count=$((no_improvement_count + 1))
            log_msg "[WARN] No improvement ($no_improvement_count/$EARLY_EXIT_THRESHOLD)"

            if [ $no_improvement_count -ge $EARLY_EXIT_THRESHOLD ]; then
                log_msg ""
                log_msg "╔════════════════════════════════════════════════════════════╗"
                log_msg "║  ⚠️ EARLY EXIT: No improvement for $EARLY_EXIT_THRESHOLD iterations        ║"
                log_msg "║  Final Pass Rate: $current_pass_rate%                              ║"
                log_msg "║  Iterations Used: $iteration                                        ║"
                log_msg "╚════════════════════════════════════════════════════════════╝"
                exit 1
            fi
        else
            log_msg "[OK] Improvement: $previous_pass_rate% → $current_pass_rate%"
            no_improvement_count=0
        fi

        previous_pass_rate=$current_pass_rate
        iteration=$((iteration + 1))
    done

    # Max iterations reached
    log_msg ""
    log_msg "╔════════════════════════════════════════════════════════════╗"
    log_msg "║  ❌ MAX_ITERATIONS_REACHED: $MAX_ITERATIONS iterations completed        ║"
    log_msg "║  Final Pass Rate: $current_pass_rate%                              ║"
    log_msg "╚════════════════════════════════════════════════════════════╝"
    exit 1
}

main "$@"
