#!/bin/bash
# ================================================================
# Phase 5C Efficient Mode - Iteration Loop Controller
# ================================================================
# This script controls the iteration loop for Phase 5C UI testing
# Uses Claude CLI with Claude In Chrome MCP for browser automation
# ================================================================

# Note: set -e removed intentionally — Claude CLI may return non-zero exit codes
# that should not terminate the iteration loop

# Fix encoding: ensure UTF-8 on Japanese Windows (Git Bash inherits CP932)
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export PYTHONIOENCODING=utf-8

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILL_REF_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
CONFIG_FILE="$SKILL_REF_DIR/config/phase5-loop-control.json"
PROMPT_FILE="$SKILL_REF_DIR/prompts/phase5c-ui-tests-efficient.md"
# PROJECT_ROOT is the user's workspace (argument or pwd)
PROJECT_ROOT="${WORKSPACE_DIR:-$(pwd)}"
LOG_DIR="$PROJECT_ROOT/test-logs"

# Create log directory
mkdir -p "$LOG_DIR"
mkdir -p "$LOG_DIR/screenshots"

# Real-time log helper: outputs to both console and realtime log file
log_msg() {
    echo "$1"
    [ -n "$REALTIME_LOG" ] && echo "[$(date +%H:%M:%S)] $1" >> "$REALTIME_LOG"
}

# ================================================================
# Check Claude In Chrome MCP Connectivity
# ================================================================
check_chrome_mcp() {
    log_msg "[CHECK] Verifying Claude In Chrome MCP..."

    # Check 1: .mcp.json exists in workspace (generated by run-all.ps1)
    if [ ! -f "$PROJECT_ROOT/.mcp.json" ]; then
        log_msg "[WARN] .mcp.json not found in $PROJECT_ROOT — Chrome MCP may not be available"
    else
        log_msg "[OK] .mcp.json found in workspace"
    fi

    # Check 2: Chrome DevTools Protocol HTTP check (fast, no claude CLI needed)
    local cdp_port
    for port in 9222 9223 9224 9225 9226 9227 9228 9229; do
        if curl -s --max-time 3 "http://127.0.0.1:$port/json/version" >/dev/null 2>&1; then
            cdp_port=$port
            break
        fi
    done

    if [ -n "$cdp_port" ]; then
        local browser_info
        browser_info=$(curl -s --max-time 3 "http://127.0.0.1:$cdp_port/json/version" 2>/dev/null | grep -o '"Browser":"[^"]*"' | head -1)
        log_msg "[OK] Chrome DevTools Protocol available on port $cdp_port ($browser_info)"
        return 0
    fi

    log_msg "[ERROR] Claude In Chrome MCP NOT available!"
    log_msg "[ERROR] Please: 1) Open Chrome with --remote-debugging-port=9222  2) Verify port is accessible"
    return 1
}

# ================================================================
# Load Configuration
# ================================================================
load_config() {
    # Default values
    MAX_ITERATIONS=15
    TARGET_PASS_RATE=100  # Phase 5C requires 100%
    EARLY_EXIT_THRESHOLD=3
    ITERATION_TIMEOUT=3600

    # Load from config file if exists
    # NOTE: pyenv-win .cmd shims break multiline python3 -c strings,
    # so we write Python code to a temp file and execute it.
    if [ -f "$CONFIG_FILE" ]; then
        local tmp_py
        tmp_py=$(mktemp /tmp/cfg_XXXXXX.py)
        cat > "$tmp_py" << 'PYEOF'
import json, sys
try:
    with open(sys.argv[1], encoding='utf-8') as f:
        cfg = json.load(f)
    print(cfg.get('phase5c_bugfix', {}).get('max_iterations', cfg.get('iteration_control', {}).get('max_iterations', 15)))
except:
    print(15)
PYEOF
        MAX_ITERATIONS=$(python3 "$tmp_py" "$CONFIG_FILE" 2>/dev/null || echo "15")
        rm -f "$tmp_py"
    fi

    # Environment variable overrides
    MAX_ITERATIONS="${BUGFIX_MAX_ITERATIONS:-$MAX_ITERATIONS}"
    TARGET_PASS_RATE="${BUGFIX_TARGET_PASS_RATE:-100}"
    EARLY_EXIT_THRESHOLD="${BUGFIX_EARLY_EXIT_THRESHOLD:-$EARLY_EXIT_THRESHOLD}"

    log_msg "============================================================"
    log_msg "Phase 5C Efficient Mode - Configuration"
    log_msg "============================================================"
    log_msg "Max Iterations: $MAX_ITERATIONS"
    log_msg "Target Pass Rate: $TARGET_PASS_RATE%"
    log_msg "Early Exit Threshold: $EARLY_EXIT_THRESHOLD"
    log_msg "Iteration Timeout: ${ITERATION_TIMEOUT}s"
    log_msg "============================================================"
}

# ================================================================
# Get Pass Rate from Results
# ================================================================
get_pass_rate() {
    RESULT_FILE="$LOG_DIR/phase5c_test_results.json"

    if [ -f "$RESULT_FILE" ]; then
        # NOTE: pyenv-win .cmd shims break multiline python3 -c strings,
        # so we write Python code to a temp file and execute it.
        local tmp_py
        tmp_py=$(mktemp /tmp/rate_XXXXXX.py)
        cat > "$tmp_py" << 'PYEOF'
import json, sys
try:
    with open(sys.argv[1], encoding='utf-8') as f:
        data = json.load(f)
    rate = 0
    rate = data.get('adjusted_pass_rate') or data.get('pass_rate') or 0
    if not rate:
        rate_str = data.get('passRate', data.get('adjustedPassRate', ''))
        if isinstance(rate_str, str):
            rate = float(rate_str.replace('%', '')) if rate_str else 0
        else:
            rate = float(rate_str) if rate_str else 0
    if not rate and 'summary' in data:
        s = data['summary']
        rate_str = s.get('passRate', s.get('pass_rate', s.get('adjusted_pass_rate', '')))
        if isinstance(rate_str, str):
            rate = float(rate_str.replace('%', '')) if rate_str else 0
        else:
            rate = float(rate_str) if rate_str else 0
    if not rate:
        total = data.get('totalTests', data.get('total_tests', data.get('total', 0)))
        passed = data.get('passed', data.get('tests_passed', 0))
        if total > 0:
            rate = round(passed / total * 100, 1)
    print(rate)
except:
    print(0)
PYEOF
        local result
        result=$(python3 "$tmp_py" "$RESULT_FILE" 2>/dev/null || echo "0")
        rm -f "$tmp_py"
        echo "$result"
    else
        echo "0"
    fi
}

# ================================================================
# Run Single Iteration
# ================================================================
run_iteration() {
    local iteration=$1
    log_msg ""
    log_msg "============================================================"
    log_msg "ITERATION $iteration/$MAX_ITERATIONS"
    log_msg "============================================================"
    
    # Build prompt with iteration context
    local prompt_file_abs="$PROMPT_FILE"
    local frontend_url="${AIDEV_FRONTEND_URL:-http://localhost:3000}"

    # Load Phase 5A test data directly into the prompt
    local test_data_context=""
    local seed_file="$LOG_DIR/test_data_seed.json"
    local auth_file="$LOG_DIR/phase5b_test_user.json"
    if [ -f "$seed_file" ]; then
        test_data_context="
=== PHASE 5A TEST DATA (ALREADY CREATED - USE THESE IDs) ===
$(cat "$seed_file")
=== END TEST DATA ===
"
        if [ -f "$auth_file" ]; then
            test_data_context="${test_data_context}
=== AUTH CREDENTIALS (use email/password to login) ===
$(cat "$auth_file")
=== END AUTH ===
"
        fi
        log_msg "[INFO] Injected Phase 5A test data into prompt"
    else
        test_data_context="
WARNING: test-logs/test_data_seed.json NOT FOUND.
You MUST create test data yourself using javascript_tool:
1. Navigate to the registration page and register a test user
2. Login with the test user credentials
3. Create entities needed for testing via the UI
4. Record all entity IDs for use in subsequent tests
"
        log_msg "[WARN] Phase 5A test data not found - Claude will create data"
    fi

    ITERATION_PROMPT="You are executing Phase 5C UI Testing, iteration ${iteration}.

IMPORTANT: The frontend is already running. Do NOT attempt to start it.
Frontend URL: ${frontend_url}
Navigate to this URL in the browser to perform UI tests.

Read and execute ALL steps from the test specification file:
${prompt_file_abs}

${test_data_context}

MANDATORY EXECUTION METHOD:
All UI tests MUST be performed via Claude In Chrome MCP browser automation ONLY.
PROHIBITED methods (do NOT use):
- Playwright / Puppeteer / Selenium
- curl / wget / python requests / httpx
- Headless browsers
- Source code inspection without rendering in a real browser
- Node.js fetch / axios
- Any non-MCP HTTP client

Required MCP tools:
- mcp__Claude_in_Chrome__tabs_context_mcp
- mcp__Claude_in_Chrome__navigate
- mcp__Claude_in_Chrome__read_page / find
- mcp__Claude_in_Chrome__computer (click/screenshot)
- mcp__Claude_in_Chrome__form_input
- mcp__Claude_in_Chrome__javascript_tool
- mcp__Claude_in_Chrome__read_network_requests
- mcp__Claude_in_Chrome__read_console_messages

STEPS (execute in order):

Step 1: Call mcp__Claude_in_Chrome__tabs_context_mcp to verify MCP connection.
  If unavailable -> stop immediately and report error. Do NOT use alternatives.

Step 2: Load test data from Phase 5A (provided above in the prompt).
  - Parse the TEST DATA section above to extract auth credentials and entity IDs.
  - Navigate to the login page and login with auth email/password.
  - NEVER hardcode id=1 or id=999. Use ONLY real IDs from test data.
  - If test data is missing or insufficient, create what you need using
    javascript_tool or by filling forms in the UI, then record the new IDs.

Step 3: Test all pages.
  - Execute 4 CORE TESTS per page (Form/Link/Button/CSS).
  - Execute 6-GATE verification per page.
  - Fix bugs immediately when found.

Step 4: Generate results file: test-logs/phase5c_test_results.json

KEY REQUIREMENTS:
1. Use Claude In Chrome MCP for browser automation (the ONLY allowed method).
2. Login using Phase 5A auth credentials (injected above).
3. Use entity IDs from test data. Never guess or hardcode IDs.
4. If test data is insufficient for a specific test, create it via javascript_tool.
5. Execute 4 CORE TESTS (Form/Link/Button/CSS) per page.
6. Execute 6-GATE verification per page.
7. Fix bugs immediately when found.
8. Generate results file: test-logs/phase5c_test_results.json
9. Target pass rate: ${TARGET_PASS_RATE}% (all pages must pass).

Report test results and GATE verification status when done."

    # Run Claude CLI via stdin pipe (NOT -p flag, which disables tools/MCP)
    # On timeout, use taskkill /T to kill entire process tree (Git Bash lacks GNU timeout/pkill)
    # NOTE: We run pipeline directly (no subshell) to avoid MSYS2 zombie subshell issue
    # where kill -0 $bg_pid keeps succeeding after all pipeline components have exited.
    # Instead, we detect completion by checking if the result JSON file was updated.
    cd "$PROJECT_ROOT"

    local RESULT_FILE="$LOG_DIR/phase5c_test_results.json"
    local iteration_start_epoch
    iteration_start_epoch=$(date +%s)

    # Write output directly to file (avoids tee buffering issue on MSYS2
    # where tee uses full buffering in pipes and loses data on taskkill)
    local ITER_LOG="$LOG_DIR/phase5c_iteration_${iteration}.log"
    : > "$ITER_LOG"

    echo "$ITERATION_PROMPT" | claude --dangerously-skip-permissions --verbose > "$ITER_LOG" 2>&1 &
    local bg_pid=$!

    # Manual timeout monitoring with result-file-based completion detection
    # Also periodically streams new log lines to console and realtime log
    local elapsed=0
    local last_line_count=0
    while kill -0 $bg_pid 2>/dev/null; do
        sleep 10
        elapsed=$((elapsed + 10))

        # Stream new lines from iteration log to console and realtime log
        if [ -f "$ITER_LOG" ]; then
            local current_line_count
            current_line_count=$(wc -l < "$ITER_LOG" 2>/dev/null || echo 0)
            if [ "$current_line_count" -gt "$last_line_count" ]; then
                local skip=$((last_line_count + 1))
                tail -n +"$skip" "$ITER_LOG" 2>/dev/null | while IFS= read -r line; do
                    echo "$line"
                    [ -n "$REALTIME_LOG" ] && echo "[$(date +%H:%M:%S)] $line" >> "$REALTIME_LOG"
                done
                last_line_count=$current_line_count
            fi
        fi

        # MSYS2 workaround: check if result file was updated after iteration started
        # This catches the case where the subshell is zombie but work is already done
        if [ -f "$RESULT_FILE" ]; then
            local current_mtime
            current_mtime=$(stat -c %Y "$RESULT_FILE" 2>/dev/null || echo 0)
            if [ "$current_mtime" -gt "$iteration_start_epoch" ]; then
                log_msg "[INFO] Result file updated — iteration complete (pipeline cleanup)"
                sleep 5  # Allow final log flush
                taskkill.exe /T /F /PID $bg_pid >/dev/null 2>&1
                kill $bg_pid 2>/dev/null
                wait $bg_pid 2>/dev/null
                return 0
            fi
        fi

        if [ $elapsed -ge $ITERATION_TIMEOUT ]; then
            log_msg "[WARN] Iteration $iteration timed out after ${ITERATION_TIMEOUT}s — killing process tree"
            # Dump remaining log lines before killing
            if [ -f "$ITER_LOG" ]; then
                local final_count
                final_count=$(wc -l < "$ITER_LOG" 2>/dev/null || echo 0)
                if [ "$final_count" -gt "$last_line_count" ]; then
                    local skip=$((last_line_count + 1))
                    tail -n +"$skip" "$ITER_LOG" 2>/dev/null | while IFS= read -r line; do
                        echo "$line"
                        [ -n "$REALTIME_LOG" ] && echo "[$(date +%H:%M:%S)] $line" >> "$REALTIME_LOG"
                    done
                fi
            fi
            # Use Windows taskkill /T to kill subshell + all child processes (claude, tee, etc.)
            taskkill.exe /T /F /PID $bg_pid >/dev/null 2>&1
            # Fallback: also try kill in case taskkill missed anything
            kill $bg_pid 2>/dev/null
            wait $bg_pid 2>/dev/null
            return 124
        fi
    done

    wait $bg_pid 2>/dev/null
    local exit_code=$?
    return $exit_code
}

# ================================================================
# Validate 6-GATE Results
# ================================================================
validate_gates() {
    RESULT_FILE="$LOG_DIR/phase5c_test_results.json"
    
    if [ ! -f "$RESULT_FILE" ]; then
        log_msg "[ERROR] Result file not found"
        return 1
    fi
    
    # NOTE: pyenv-win .cmd shims break multiline python3 -c strings,
    # so we write Python code to a temp file and execute it.
    local tmp_py
    tmp_py=$(mktemp /tmp/gate_XXXXXX.py)
    cat > "$tmp_py" << 'PYEOF'
import json, sys
with open(sys.argv[1], encoding='utf-8') as f:
    data = json.load(f)
gate6 = data.get('gate6_cross_validation', {})
if gate6.get('verdict') == 'CONTRADICTIONS_DETECTED':
    print('[FATAL] GATE 6 detected contradictions - test run invalid')
    sys.exit(1)
gate_summary = data.get('gate_summary', {})
gate1_failed = gate_summary.get('gate1_css_failed', 0)
gate2_failed = gate_summary.get('gate2_content_failed', 0)
gate3_blocked = gate_summary.get('gate3_loop_blocked', 0)
gate4_failed = gate_summary.get('gate4_screenshot_failed', 0)
if gate1_failed > 0:
    print(f'[WARN] GATE 1 (CSS) failed on {gate1_failed} pages')
if gate2_failed > 0:
    print(f'[WARN] GATE 2 (Content) failed on {gate2_failed} pages')
if gate3_blocked > 0:
    print(f'[BLOCKED] GATE 3 (Loop) blocked {gate3_blocked} pages')
if gate4_failed > 0:
    print(f'[WARN] GATE 4 (Screenshot) failed on {gate4_failed} pages')
print('[OK] GATE validation complete')
PYEOF
    python3 "$tmp_py" "$RESULT_FILE" 2>/dev/null
    rm -f "$tmp_py"
}

# ================================================================
# Main Loop
# ================================================================
main() {
    log_msg "+============================================================+"
    log_msg "|  Phase 5C Efficient Mode - Iteration Loop Controller       |"
    log_msg "+============================================================+"

    load_config

    # Pre-check: Claude In Chrome MCP must be available
    if ! check_chrome_mcp; then
        log_msg "[FATAL] Cannot proceed without Claude In Chrome MCP."
        exit 1
    fi

    iteration=1
    no_improvement_count=0
    previous_pass_rate=0

    while [ $iteration -le $MAX_ITERATIONS ]; do
        # Run iteration
        run_iteration $iteration || true

        # Validate GATE results
        validate_gates || log_msg "[WARN] GATE validation had issues"

        # Get pass rate from results
        current_pass_rate=$(get_pass_rate)
        log_msg ""
        log_msg "[RESULT] Pass Rate: $current_pass_rate%"

        # Check if target achieved (100% for Phase 5C)
        if [ $(python3 -c "print(1 if $current_pass_rate >= $TARGET_PASS_RATE else 0)" 2>/dev/null || echo "0") -eq 1 ]; then
            log_msg ""
            log_msg "+============================================================+"
            log_msg "|  [OK] SUCCESS: All pages passed!                            |"
            log_msg "|  Final Pass Rate: $current_pass_rate%                              |"
            log_msg "|  Iterations Used: $iteration                                        |"
            log_msg "+============================================================+"
            exit 0
        fi

        # Check early exit (strict less-than: plateau is NOT treated as no-improvement)
        if [ $(python3 -c "print(1 if $current_pass_rate < $previous_pass_rate else 0)" 2>/dev/null || echo "0") -eq 1 ]; then
            no_improvement_count=$((no_improvement_count + 1))
            log_msg "[WARN] No improvement ($no_improvement_count/$EARLY_EXIT_THRESHOLD)"

            if [ $no_improvement_count -ge $EARLY_EXIT_THRESHOLD ]; then
                log_msg ""
                log_msg "+============================================================+"
                log_msg "|  [WARN] EARLY EXIT: No improvement for $EARLY_EXIT_THRESHOLD iterations    |"
                log_msg "|  Final Pass Rate: $current_pass_rate%                              |"
                log_msg "|  Remaining pages need fixes                                |"
                log_msg "+============================================================+"
                exit 1
            fi
        else
            log_msg "[OK] Improvement: $previous_pass_rate% → $current_pass_rate%"
            no_improvement_count=0
        fi

        previous_pass_rate=$current_pass_rate
        iteration=$((iteration + 1))
    done

    # Max iterations reached
    log_msg ""
    log_msg "+============================================================+"
    log_msg "|  [FAIL] MAX_ITERATIONS_REACHED: $MAX_ITERATIONS iterations completed    |"
    log_msg "|  Final Pass Rate: $current_pass_rate%                              |"
    log_msg "|  Some pages still have issues                              |"
    log_msg "+============================================================+"
    exit 1
}

main "$@"
