export const browserCoreExamples = [
  "winclaw browser status",
  "winclaw browser start",
  "winclaw browser stop",
  "winclaw browser tabs",
  "winclaw browser open https://example.com",
  "winclaw browser focus abcd1234",
  "winclaw browser close abcd1234",
  "winclaw browser screenshot",
  "winclaw browser screenshot --full-page",
  "winclaw browser screenshot --ref 12",
  "winclaw browser snapshot",
  "winclaw browser snapshot --format aria --limit 200",
  "winclaw browser snapshot --efficient",
  "winclaw browser snapshot --labels",
];

export const browserActionExamples = [
  "winclaw browser navigate https://example.com",
  "winclaw browser resize 1280 720",
  "winclaw browser click 12 --double",
  'winclaw browser type 23 "hello" --submit',
  "winclaw browser press Enter",
  "winclaw browser hover 44",
  "winclaw browser drag 10 11",
  "winclaw browser select 9 OptionA OptionB",
  "winclaw browser upload /tmp/file.pdf",
  'winclaw browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "winclaw browser dialog --accept",
  'winclaw browser wait --text "Done"',
  "winclaw browser evaluate --fn '(el) => el.textContent' --ref 7",
  "winclaw browser console --level error",
  "winclaw browser pdf",
];
