name: WinClaw
options:
  bundleIdPrefix: ai.winclaw
  deploymentTarget:
    iOS: "18.0"
  xcodeVersion: "16.0"

settings:
  base:
    SWIFT_VERSION: "6.0"

packages:
  WinClawKit:
    path: ../shared/WinClawKit
  Swabble:
    path: ../../Swabble

schemes:
  WinClaw:
    shared: true
    build:
      targets:
        WinClaw: all
    test:
      targets:
        - WinClawTests

targets:
  WinClaw:
    type: application
    platform: iOS
    sources:
      - path: Sources
    dependencies:
      - package: WinClawKit
      - package: WinClawKit
        product: WinClawChatUI
      - package: WinClawKit
        product: WinClawProtocol
      - package: Swabble
        product: SwabbleKit
      - sdk: AppIntents.framework
    preBuildScripts:
      - name: SwiftFormat (lint)
        basedOnDependencyAnalysis: false
        inputFileLists:
          - $(SRCROOT)/SwiftSources.input.xcfilelist
        script: |
          set -euo pipefail
          export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
          if ! command -v swiftformat >/dev/null 2>&1; then
            echo "error: swiftformat not found (brew install swiftformat)" >&2
            exit 1
          fi
          swiftformat --lint --config "$SRCROOT/../../.swiftformat" \
            --filelist "$SRCROOT/SwiftSources.input.xcfilelist"
      - name: SwiftLint
        basedOnDependencyAnalysis: false
        inputFileLists:
          - $(SRCROOT)/SwiftSources.input.xcfilelist
        script: |
          set -euo pipefail
          export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
          if ! command -v swiftlint >/dev/null 2>&1; then
            echo "error: swiftlint not found (brew install swiftlint)" >&2
            exit 1
          fi
          swiftlint lint --config "$SRCROOT/.swiftlint.yml" --use-script-input-file-lists
    settings:
      base:
        CODE_SIGN_IDENTITY: "Apple Development"
        CODE_SIGN_STYLE: Manual
        DEVELOPMENT_TEAM: Y5PE65HELJ
        PRODUCT_BUNDLE_IDENTIFIER: ai.winclaw.ios
        PROVISIONING_PROFILE_SPECIFIER: "ai.winclaw.ios Development"
        SWIFT_VERSION: "6.0"
        SWIFT_STRICT_CONCURRENCY: complete
        ENABLE_APPINTENTS_METADATA: NO
    info:
      path: Sources/Info.plist
      properties:
        CFBundleDisplayName: WinClaw
        CFBundleIconName: AppIcon
        CFBundleShortVersionString: "2026.2.9"
        CFBundleVersion: "20260202"
        UILaunchScreen: {}
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        UIBackgroundModes:
          - audio
        NSLocalNetworkUsageDescription: WinClaw discovers and connects to your WinClaw gateway on the local network.
        NSAppTransportSecurity:
          NSAllowsArbitraryLoadsInWebContent: true
        NSBonjourServices:
          - _winclaw-gw._tcp
        NSCameraUsageDescription: WinClaw can capture photos or short video clips when requested via the gateway.
        NSLocationWhenInUseUsageDescription: WinClaw uses your location when you allow location sharing.
        NSLocationAlwaysAndWhenInUseUsageDescription: WinClaw can share your location in the background when you enable Always.
        NSMicrophoneUsageDescription: WinClaw needs microphone access for voice wake.
        NSSpeechRecognitionUsageDescription: WinClaw uses on-device speech recognition for voice wake.
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight

  WinClawTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests
    dependencies:
      - target: WinClaw
      - package: Swabble
        product: SwabbleKit
      - sdk: AppIntents.framework
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ai.winclaw.ios.tests
        SWIFT_VERSION: "6.0"
        SWIFT_STRICT_CONCURRENCY: complete
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/WinClaw.app/WinClaw"
        BUNDLE_LOADER: "$(TEST_HOST)"
    info:
      path: Tests/Info.plist
      properties:
        CFBundleDisplayName: WinClawTests
        CFBundleShortVersionString: "2026.2.9"
        CFBundleVersion: "20260202"
